Repository mapbox/mapbox-vision-android, pull requests merged in 2019-10, with the labels that each got.

#210 Knn examples fix
  Examples/build.gradle
  Examples/src/main/java/com/mapbox/vision/examples/ArActivity.java
  Examples/src/main/java/com/mapbox/vision/examples/BaseActivity.java
  Examples/src/main/java/com/mapbox/vision/examples/ExternalCameraSource.java
  Examples/src/main/java/com/mapbox/vision/examples/SafetyActivity.java
  Examples/src/main/kotlin/com/mapbox/vision/examples/ArActivityKt.kt
  Examples/src/main/kotlin/com/mapbox/vision/examples/ExternalCameraSourceKt.kt
  Examples/src/main/kotlin/com/mapbox/vision/examples/SafetyActivityKt.kt
  build.gradle
  gradle/versions.gradle
Labels: Android, P0

#212 Release 0.10.0
  CHANGELOG.md
  Examples/src/main/java/com/mapbox/vision/examples/ExternalCameraSource.java
  Examples/src/main/java/com/mapbox/vision/examples/SafetyActivity.java
  Examples/src/main/kotlin/com/mapbox/vision/examples/ExternalCameraSourceKt.kt
  Examples/src/main/kotlin/com/mapbox/vision/examples/SafetyActivityKt.kt
  gradle/versions.gradle
Labels: Android

#213 Release 0.10.1
  CHANGELOG.md
Labels: Android, DO NOT MERGE
