Repository mapbox/mapbox-vision-android, pull requests merged in 2019-09, with the labels that each got.

#199 Fix Examples
  Examples/src/main/java/com/mapbox/vision/examples/ArActivity.java
  Examples/src/main/java/com/mapbox/vision/examples/BaseActivity.java
  Examples/src/main/java/com/mapbox/vision/examples/ExternalCameraSource.java
  Examples/src/main/java/com/mapbox/vision/examples/SafetyActivity.java
  Examples/src/main/kotlin/com/mapbox/vision/examples/ArActivityKt.kt
  Examples/src/main/kotlin/com/mapbox/vision/examples/ExternalCameraSourceKt.kt
  Examples/src/main/kotlin/com/mapbox/vision/examples/SafetyActivityKt.kt
  MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/SurfaceVideoRecorder.kt
Labels: Android, Bug, P1

#202 Fix ktlint warnings
  MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/manager/DelegateVisionManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/sync/syncmanager/TelemetrySyncManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/Camera2VideoSourceImpl.kt
  MapboxVision/src/test/java/com/mapbox/vision/sync/TelemetryEnvironmentTest.kt
Labels: Android, P0

#204 Release candidate 0.8.1 to Release 0.8.1
  CHANGELOG.md
  MapboxVision/src/main/java/com/mapbox/vision/VisionManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/manager/DelegateVisionManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/sync/syncmanager/TelemetrySyncManager.kt
  MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/Camera2VideoSourceImpl.kt
  MapboxVision/src/main/java/com/mapbox/vision/video/videosource/camera/SurfaceVideoRecorder.kt
  MapboxVision/src/test/java/com/mapbox/vision/sync/TelemetryEnvironmentTest.kt
Labels: Android, P0

#208 Add github/stale.yml
  .github/stale.yml
Labels: nostale
